name: test-versions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo: ['0.49.2', '0.50', '0.60.0', '0.70.0', '0.80.0', '0.90.0', '0.91.0', '0.92.0']
    
      fail-fast: true


    steps:
      - uses: actions/checkout@master

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install tools
        run: |
          sudo apt install curl jq
          npm i -g postcss postcss-cli autoprefixer

      - name: Test with Hugo ${{ matrix.hugo }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ matrix.hugo }}
          extended: true

      - name: Build with Hugo ${{ matrix.hugo }}
        run: |
          cd exampleSite && HUGO_THEME="hugo-theme-introduction" hugo --themesDir ../.. -v

      - name: Test HTML from Hugo ${{ matrix.hugo }}
        run: docker run -v ${GITHUB_WORKSPACE}/public/:/mnt 18fgsa/html-proofer mnt --disable-external
